# SPDX-FileCopyrightText: 2022 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

variables:
  RELEASE_REGISTRY: docker.io
  RELEASE_REGISTRY_IMAGE: index.docker.io/magentaaps/os2mo-amqp-trigger-engagement-elevator

  IMAGE_SHA: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}

  PYTEST_COV_MODULE: elevate_manager
  PYTEST_COV_FAIL_UNDER: 100

  PYTEST_EXTRA_FLAGS: "-n auto"
  PRECOMMIT_USE_POETRY: "true"

stages:
  - lint
  - test
  - coverage
  - build
  - release
  - deploy


workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

include:
  # See https://git.magenta.dk/labs/salt-automation/-/tree/master/gitlab-ci-templates/common

    # Runs linting
  - project: labs/salt-automation
    ref: master
    file: /gitlab-ci-templates/common/pre-commit.v1.yml

  # Runs testing
  - project: labs/salt-automation
    ref: master
    file: /gitlab-ci-templates/python/pytest.v1.yml


  # Kører build
  - project: labs/salt-automation
    file: /gitlab-ci-templates/common/docker-build.v1.yml



  # Kører automatisk release
  - project: labs/salt-automation
    file: /gitlab-ci-templates/common/docker-release.v1.yml
