# SPDX-FileCopyrightText: 2022 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [ "--py310-plus" ]
        exclude: ^elevate_manager/models/

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        exclude: ^elevate_manager/models/

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        exclude: ^elevate_manager/models/

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [ "--extend-ignore=B008,W503,E203", "--max-line-length=101" ]
        exclude: ^elevate_manager/models/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        args: [ --config-file=pyproject.toml ]
        additional_dependencies:
          - aiohttp
          - fastapi
          - httpx
          - os2mo_dar_client==1.0.1
          - pydantic
          - starlette_context
          - strawberry-graphql
          - structlog
          - prometheus_client
          - types-python-dateutil
          - pytest
        exclude: ^elevate_manager/models/

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        files: \.(js|vue|css|html)$
        exclude: ^elevate_manager/models/

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        files: backend/mora/graphapi/
        args: [ "--convention=google", "--add-ignore=D1" ]
        additional_dependencies:
          - toml
        exclude: ^elevate_manager/models/


  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: check-builtin-literals
        exclude: ^elevate_manager/models/
      - id: check-byte-order-marker
        exclude: ^elevate_manager/models/
      - id: check-docstring-first
        exclude: ^elevate_manager/models/
      - id: check-executables-have-shebangs
        exclude: ^elevate_manager/models/
      - id: check-merge-conflict
        exclude: ^elevate_manager/models/
      - id: check-yaml
        exclude: ^elevate_manager/models/
      - id: end-of-file-fixer
        exclude: ^elevate_manager/models/
      - id: pretty-format-json
        exclude: ^elevate_manager/models/
      - id: mixed-line-ending
        exclude: ^elevate_manager/models/
      - id: trailing-whitespace
        exclude: ^elevate_manager/models/


  - repo: https://github.com/dosisod/refurb
    rev: v1.15.0
    hooks:
      - id: refurb
        exclude: ^elevate_manager/models/

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.19
    hooks:
      - id: shellcheck
