# SPDX-FileCopyrightText: 2022 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
version: "3.9"
services:
  elevator:
    build: .
    command: ["uvicorn", "--factory", "app.main:create_app", "--host", "0.0.0.0", "--reload"]
    env_file:
      - dev-environment/elevator.env
    environment:
      LOG_LEVEL: DEBUG
    networks:
      - os2mo_default
    volumes:
      - ./:/app/
    ports:
      - "8100:8000"

networks:
  os2mo_default:
    external: true
