# Generated by ariadne-codegen on 2025-02-06 17:54
# Source: queries.graphql

from typing import List, Optional
from uuid import UUID

from .base_model import BaseModel


class ManagerEngagements(BaseModel):
    managers: "ManagerEngagementsManagers"


class ManagerEngagementsManagers(BaseModel):
    objects: List["ManagerEngagementsManagersObjects"]


class ManagerEngagementsManagersObjects(BaseModel):
    current: Optional["ManagerEngagementsManagersObjectsCurrent"]


class ManagerEngagementsManagersObjectsCurrent(BaseModel):
    employee: Optional[List["ManagerEngagementsManagersObjectsCurrentEmployee"]]
    org_unit_uuid: UUID


class ManagerEngagementsManagersObjectsCurrentEmployee(BaseModel):
    engagements: List["ManagerEngagementsManagersObjectsCurrentEmployeeEngagements"]


class ManagerEngagementsManagersObjectsCurrentEmployeeEngagements(BaseModel):
    uuid: UUID


ManagerEngagements.update_forward_refs()
ManagerEngagementsManagers.update_forward_refs()
ManagerEngagementsManagersObjects.update_forward_refs()
ManagerEngagementsManagersObjectsCurrent.update_forward_refs()
ManagerEngagementsManagersObjectsCurrentEmployee.update_forward_refs()
ManagerEngagementsManagersObjectsCurrentEmployeeEngagements.update_forward_refs()
