# Generated by ariadne-codegen on 2025-02-05 16:31
# Source: queries.graphql
from typing import List
from typing import Optional
from uuid import UUID

from .base_model import BaseModel


class OrgUnitManagers(BaseModel):
    org_units: "OrgUnitManagersOrgUnits"


class OrgUnitManagersOrgUnits(BaseModel):
    objects: list["OrgUnitManagersOrgUnitsObjects"]


class OrgUnitManagersOrgUnitsObjects(BaseModel):
    current: Optional["OrgUnitManagersOrgUnitsObjectsCurrent"]


class OrgUnitManagersOrgUnitsObjectsCurrent(BaseModel):
    name: str
    uuid: UUID
    managers: list["OrgUnitManagersOrgUnitsObjectsCurrentManagers"]


class OrgUnitManagersOrgUnitsObjectsCurrentManagers(BaseModel):
    uuid: UUID


OrgUnitManagers.update_forward_refs()
OrgUnitManagersOrgUnits.update_forward_refs()
OrgUnitManagersOrgUnitsObjects.update_forward_refs()
OrgUnitManagersOrgUnitsObjectsCurrent.update_forward_refs()
OrgUnitManagersOrgUnitsObjectsCurrentManagers.update_forward_refs()
