# Generated by ariadne-codegen on 2025-02-06 17:54
# Source: queries.graphql

from typing import List, Optional
from uuid import UUID

from .base_model import BaseModel


class OrgUnitManagers(BaseModel):
    org_units: "OrgUnitManagersOrgUnits"


class OrgUnitManagersOrgUnits(BaseModel):
    objects: List["OrgUnitManagersOrgUnitsObjects"]


class OrgUnitManagersOrgUnitsObjects(BaseModel):
    current: Optional["OrgUnitManagersOrgUnitsObjectsCurrent"]


class OrgUnitManagersOrgUnitsObjectsCurrent(BaseModel):
    name: str
    uuid: UUID
    managers: List["OrgUnitManagersOrgUnitsObjectsCurrentManagers"]


class OrgUnitManagersOrgUnitsObjectsCurrentManagers(BaseModel):
    uuid: UUID


OrgUnitManagers.update_forward_refs()
OrgUnitManagersOrgUnits.update_forward_refs()
OrgUnitManagersOrgUnitsObjects.update_forward_refs()
OrgUnitManagersOrgUnitsObjectsCurrent.update_forward_refs()
OrgUnitManagersOrgUnitsObjectsCurrentManagers.update_forward_refs()
