# Generated by ariadne-codegen on 2025-02-05 16:31
from collections.abc import Callable
from typing import Any
from typing import Dict

SCALARS_PARSE_FUNCTIONS: dict[Any, Callable[[Any], Any]] = {}
SCALARS_SERIALIZE_FUNCTIONS: dict[Any, Callable[[Any], Any]] = {}
