# Generated by ariadne-codegen on 2025-02-18 09:26
from collections.abc import Callable
from typing import Any

SCALARS_PARSE_FUNCTIONS: dict[Any, Callable[[Any], Any]] = {}
SCALARS_SERIALIZE_FUNCTIONS: dict[Any, Callable[[Any], Any]] = {}
