# SPDX-FileCopyrightText: 2022 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

########################### DO NOT EDIT FILE ############################
#
# All code in this module is auto generated by Quicktype
# (see https://github.com/quicktype/quicktype) via the command
# $ quicktype --src-lang graphql --lang py --python-version 3.7 \
#   --graphql-introspect https://moradev.magentahosted.dk/graphql/v3 \
#   get_manager_engagements_org_unit_uuids.graphql --just-types
#
# where the content of the file get_manager_engagements_org_unit_uuids.graphql is
#
# query GetManagerEngagementsOrgUnitUuids {
#   managers {
#     objects {
#       employee {
#         engagements {
#           uuid
#         }
#       }
#       org_unit_uuid
#     }
#   }
# }

from dataclasses import dataclass
from typing import List, Optional


@dataclass
class Engagement:
    uuid: str


@dataclass
class Employee:
    engagements: List[Engagement]


@dataclass
class Manager:
    org_unit_uuid: str
    employee: Optional[List[Employee]] = None


@dataclass
class ManagerResponse:
    objects: List[Manager]


@dataclass
class Data:
    managers: List[ManagerResponse]


@dataclass
class Error:
    message: str


@dataclass
class GetManagerEngagementsOrgUnitUuids:
    data: Optional[Data] = None
    errors: Optional[List[Error]] = None
