# SPDX-FileCopyrightText: 2022 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

########################### DO NOT EDIT FILE ############################
#
# All code in this module is auto generated by Quicktype
# (see https://github.com/quicktype/quicktype) via the command
# $ quicktype --src-lang graphql --lang py --python-version 3.7 \
#   --graphql-introspect https://moradev.magentahosted.dk/graphql/v3 \
#   get_org_unit_levels.graphql --just-types
#
# where the content of the file get_org_unit_levels.graphql is
#
# query Engagements {
#   managers {
#     objects {
#       employee {
#         engagements {
#           uuid
#           user_key
#           org_unit {
#             name
#             uuid
#             parent_uuid
#             org_unit_level {
#               name
#               uuid
#             }
#           }
#         }
#       }
#       org_unit {
#         name
#         uuid
#         org_unit_level {
#           name
#           uuid
#         }
#       }
#     }
#   }
# }
#
# Use the dataclasses below from code by calling the Pydantic function
# org_unit_levels = parse_obj_as(GetOrgUnitLevels, {... dict with GraphQL response ...})

from dataclasses import dataclass
from typing import Optional, List


@dataclass
class Class:
    name: str
    uuid: Optional[str] = None


@dataclass
class OrganisationUnit:
    name: str
    uuid: Optional[str] = None
    parent_uuid: Optional[str] = None
    org_unit_level: Optional[Class] = None


@dataclass
class Engagement:
    org_unit: List[OrganisationUnit]
    uuid: Optional[str] = None
    user_key: Optional[str] = None


@dataclass
class Employee:
    engagements: List[Engagement]


@dataclass
class Manager:
    employee: List[Employee]
    org_unit: List[OrganisationUnit]


@dataclass
class ManagerResponse:
    objects: List[Manager]


@dataclass
class Data:
    managers: List[ManagerResponse]


@dataclass
class Error:
    message: str


@dataclass
class GetOrgUnitLevels:
    data: Optional[Data] = None
    errors: Optional[List[Error]] = None
