# SPDX-FileCopyrightText: 2022 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

########################### DO NOT EDIT FILE ############################
#
# All code in this module is auto generated by Quicktype
# (see https://github.com/quicktype/quicktype) via the command
# $ quicktype --src-lang graphql --lang py --python-version 3.7 \
#   --graphql-introspect https://moradev.magentahosted.dk/graphql/v3 \
#   get_manager_engagements.graphql --just-types
#
# where the content of the file get_manager_engagements.graphql is
#
# query GetManagerEngagements {
#   managers {
#     objects {
#       employee {
#         engagements {
#           uuid
#         }
#       }
#     }
#   }
# }

from dataclasses import dataclass
from typing import Optional, List


@dataclass
class Engagement:
    uuid: Optional[str] = None


@dataclass
class Employee:
    engagements: List[Engagement]


@dataclass
class Manager:
    employee: List[Employee]


@dataclass
class ManagerResponse:
    objects: List[Manager]


@dataclass
class Data:
    managers: List[ManagerResponse]


@dataclass
class Error:
    message: str


@dataclass
class GetManagerEngagements:
    data: Optional[Data] = None
    errors: Optional[List[Error]] = None
