# SPDX-FileCopyrightText: 2022 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

########################### DO NOT EDIT FILE ############################
#
# All code in this module is auto generated by Quicktype
# (see https://github.com/quicktype/quicktype) via the command
# $ quicktype --src-lang graphql --lang py --python-version 3.7 \
#   --graphql-introspect https://moradev.magentahosted.dk/graphql/v3 \
#   get_existing_managers.graphql --just-types
#
# where the content of the file get_existing_managers.graphql is
#
# query GetManagers {
#     org_units {
#         objects {
#             managers {
#                 uuid
#                 user_key
#             }
#         }
#     }
# }
#
# Use the dataclasses below from code by calling the Pydantic function
# parse_obj_as(GetExistingManagers, {... dict with GraphQL response ...})

from dataclasses import dataclass
from typing import Optional, List


@dataclass
class Manager:
    uuid: Optional[str] = None
    user_key: Optional[str] = None


@dataclass
class OrganisationUnit:
    managers: List[Manager]


@dataclass
class OrganisationUnitResponse:
    objects: List[OrganisationUnit]


@dataclass
class Data:
    org_units: List[OrganisationUnitResponse]


@dataclass
class Error:
    message: str


@dataclass
class GetExistingManagers:
    data: Optional[Data] = None
    errors: Optional[List[Error]] = None
